apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  selector:
    app: nginx-ingress
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: waf-enforcer # optionally, for referencing in the 'app_protect_enforcer_address directive'.
spec:
  selector:
    app: nginx-ingress
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
