apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apBundle: "nap5-policy.tgz"
    securityLogs:
    - enable: true
      apLogBundle: "nap5-log-profile.tgz"
      logDest: "syslog:server=10.1.1.9:8515"
